apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
      matchLabels:
        app: queue
  replicas: 1
  template:
    metadata:
      labels:
        app: queue
        track: stable
    spec:
      containers:
        - name: queue
          image: "youracr.azurecr.io/rabbitmq:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 15672
            - name: rabbitmq
              containerPort: 5672
          volumeMounts:
            - mountPath: "/var/lib/rabbitmq/mnesia"
              name: rabbitmq
      nodeSelector:
        agentpool: agentpool
      volumes:
        - name: rabbitmq
          persistentVolumeClaim:
            claimName: rabbitmq-data